<!DOCTYPE html>
<html>
<head>
	<title>Test Note App</title>
	<link rel="stylesheet" type="text/css" href="css/styles.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
	<script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>

	<div class="container">
		<?php require ROOT_DIR . '/html/' . $_action_name . '.phtml' ?>
		
	</div>

	<script src="js/main.js"></script>
</body>
</html>