<div class="container-scroller">

	<h2>Test Note Title</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat.</p>

<br>
<br>

		<a href="?" class="button gray">&larr; Назад</a>
		<a href="?action=edit" class="button">Редактировать</a>
		<a href="?action=delete" class="button red">Удалить</a>

	

</div>